spring.application.name=ai-expense-analyzer
server.port=8080

spring.data.mongodb.uri=mongodb+srv://lokeshgada7_db_user:1W7EMFDqq9ikLSRQ@cluster0.ohrcg5w.mongodb.net/expense_db?retryWrites=true&w=majority